spring:
  application:
    name: flowableDemo

  # ==================== ?????????? MySQL? ====================
  datasource:
    url: jdbc:mysql://localhost:3306/flowable_learning?characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: lxy666666
    driver-class-name: com.mysql.cj.jdbc.Driver

  # ???Hikari ?????????????
  hikari:
    maximum-pool-size: 20
    minimum-idle: 5

# ==================== Flowable ?? ====================
flowable:
  # ??????????/???????????? false?
  database-schema-update: true
  
  # ??????????????? resources/processes ????
  process:
    deployment-mode: default   # ? "single-resource"
  
  # ??????????????????
  db-history-used: true
  history-level: full        # full / activity / audit / none

  # ????????????????????
  # async-executor-activate: true

# ==================== ????????? Flowable ??? ====================
logging:
  level:
    org.flowable: DEBUG      # ? Flowable ????
    com.myfinal: DEBUG


server:
  port: 9070