spring:
  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    url: jdbc:mysql://localhost:3306/redis_learning?characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: lxy666666
    driver-class-name: com.mysql.cj.jdbc.Driver

  cache:
    caffeine:
      spec: maximumSize=100,expireAfterWrite=30m

server:
  port: 18700

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true

pingcode:
  app-name: redis-demo
  rest-api-root: https://open.pingcode.com
  oauth2-root: https://open.pingcode.com/oauth2
  token:
    grant-type: client_credentials
    client-id: nNoyvLLzACRK
    client-secret: oJIdcepaviPINVXBalIJSUbp

logging:
  level:
    com.myfinal.redis.service: DEBUG
    com.myfinal.redis.controller: INFO
